import { BuildingType, AnimalType, AdType } from "../enum"

export const Sprites = {
    MEAT_MAN: 'meat_guy',
    ANIMAL_DEALER: 'animal_dealer',
    LOAN_SHARK: 'shady_lender',
    COPS: 'cop',
    CASH: 'cash',
    MEAT: 'meat',
    TUTORIAL: 'tutorial',
    no_employee: 'no_employee',
    Persons: [
        'person1',
        'person2',
        'person3',
        'person4',
        'person5',
        'person6',
        'person7'
    ],
    PersonVehicles: [
        'jalopy',
        'vintage',
        'tuck',
        'bus',
        'taxi',
        'fancy'
    ]
}

export const defaults = [
    { key: 'tiles', resource: require('./tiles.png'), type: 'image' },
    { key: 'gallet_city', resource: require('./galletcity_tiles.png'), type: 'image' },
    { key: 'meat_truck', resource: require('./meat_truck.png'), type: 'image' },
    { key: 'animal_truck', resource: require('./animal_truck.png'), type: 'image' },
    { key: 'shady_lender', resource: require('./people/shady_investor.png'), type: 'image' },
    { key: 'swat_van', resource: require('./swat_van.png'), type: 'image' },
    { key: 'marker', resource: require('./marker.png'), type: 'image' },
    { key: 'fast', resource: require('./fast_car.png'), type: 'image' },
    { key: 'bus', resource: require('./tour_bus.png'), type: 'image' },
    { key: 'tuck', resource: require('./tuck.png'), type: 'image' },
    { key: 'booth', resource: require('./entrance.png'), type: 'image' },
    { key: 'vintage', resource: require('./vintage_car.png'), type: 'image' },
    { key: 'fancy', resource: require('./buyer_car.png'), type: 'image' },
    { key: 'camo', resource: require('./camo.jpg'), type: 'image' },
    { key: 'taxi', resource: require('./taxi.png'), type: 'image' },
    { key: 'jalopy', resource: require('./jalopy_car.png'), type: 'image' },
    { key: 'meat1', resource: require('./food/meat1.png'), type: 'image' },
    { key: 'meat2', resource: require('./food/meat2.png'), type: 'image' },
    { key: 'meat3', resource: require('./food/meat3.png'), type: 'image' },
    { key: 'meat4', resource: require('./food/meat4.png'), type: 'image' },
    { key: 'meat5', resource: require('./food/meat5.png'), type: 'image' },
    { key: 'tutorial', resource: require('./people/tutorial.png'), type: 'image' },
    { key: 'no_employee', resource: require('./no_employee.png'), type: 'image' },
    { key: AnimalType.BEAR, resource: require('./animals/bear.png'), type: 'image' },
    { key: AnimalType.LION, resource: require('./animals/lion.png'), type: 'image' },
    { key: AnimalType.MONKEY, resource: require('./animals/monkey.png'), type: 'image' },
    { key: AnimalType.TIGER, resource: require('./animals/tiger.png'), type: 'image' },
    { key: AnimalType.LEMUR, resource: require('./animals/lemur.png'), type: 'image' },
    { key: AnimalType.LIGER, resource: require('./animals/liger.png'), type: 'image' },
    { key: Sprites.ANIMAL_DEALER, resource: require('./people/animal_dealer.png'), type: 'image' },
    { key: Sprites.COPS, resource: require('./people/cop.png'), type: 'image' },
    { key: Sprites.MEAT_MAN, resource: require('./people/meat_man.png'), type: 'image' },
    { key: BuildingType.L_PEN, resource: require('./buildings/l_pen.png'), type: 'image'},
    { key: BuildingType.M_PEN, resource: require('./buildings/m_pen.png'), type: 'image'},
    { key: BuildingType.S_PEN, resource: require('./buildings/s_pen.png'), type: 'image'},
    { key: BuildingType.GIFT_SHOP, resource: require('./buildings/giftshop.png'), type: 'image'},
    { key: BuildingType.HOUSING, resource: require('./buildings/housing.png'), type: 'image'},
    { key: BuildingType.SNACK_HUT, resource: require('./buildings/snack_hut.png'), type: 'image'},
    { key: BuildingType.PETTING_ARENA, resource: require('./buildings/petting_arena.png'), type: 'image'},
    { key: BuildingType.STUDIO, resource: require('./buildings/studio.png'), type: 'image'},
    { key: 'step', resource: require('./audio/step.mp3'), type: 'audio' },
    { key: 'build', resource: require('./audio/build.mp3'), type: 'audio' },
    { key: 'old', resource: require('./audio/jalopy.mp3'), type: 'audio' },
    { key: 'cops', resource: require('./audio/rock.mp3'), type: 'audio' },
    { key: 'error', resource: require('./audio/error.mp3'), type: 'audio' },
    { key: 'end', resource: require('./audio/end.mp3'), type: 'audio' },
    { key: 'destroyed', resource: require('./audio/destroyed.mp3'), type: 'audio' },
    { key: 'register', resource: require('./audio/register.mp3'), type: 'audio' },
    { key: 'meat', resource: require('./audio/meat.mp3'), type: 'audio' },
    { key: 'roar', resource: require('./audio/roar.mp3'), type: 'audio' },
    { key: 'fast', resource: require('./audio/fast.mp3'), type: 'audio' },
    { key: 'mumbler', resource: require('./audio/mumbler.mp3'), type: 'audio' },
    { key: 'gameplay', resource: require('./audio/gameplay.mp3'), type: 'audio' },
    { key: 'selected', resource: require('./selected.png'), type: 'image'},
    { key: 'map', resource: require('./map.json'), type: 'tilemapTiledJSON', data: {}},
    { key: 'tiles_sprites', resource: require('./tiles.png'), type: 'spritesheet', data: { frameWidth: 8, frameHeight: 8 }},
    { key: 'person1', resource: require('./people/person1.png'), type: 'spritesheet', data: { frameWidth: 32, frameHeight: 32 }},
    { key: 'person2', resource: require('./people/person2.png'), type: 'spritesheet', data: { frameWidth: 32, frameHeight: 32 }},
    { key: 'person3', resource: require('./people/person3.png'), type: 'spritesheet', data: { frameWidth: 32, frameHeight: 32 }},
    { key: 'person4', resource: require('./people/person4.png'), type: 'spritesheet', data: { frameWidth: 32, frameHeight: 32 }},
    { key: 'person5', resource: require('./people/person5.png'), type: 'spritesheet', data: { frameWidth: 32, frameHeight: 32 }},
    { key: 'person6', resource: require('./people/person6.png'), type: 'spritesheet', data: { frameWidth: 32, frameHeight: 32 }},
    { key: 'person7', resource: require('./people/person7.png'), type: 'spritesheet', data: { frameWidth: 32, frameHeight: 32 }},
    { key: 'time', resource: require('./time.png'), type: 'image' },
    { key: 'avatar', resource: require('./avatar.png'),  type: 'spritesheet', data: { frameWidth: 16, frameHeight: 20 }},
    { key: 'meat', resource: require('./food/meats.png'),  type: 'spritesheet', data: { frameWidth: 24, frameHeight: 24 }},
]

export const SpriteIndexes = {
    plot: 8,
    avatarwork: 3,
    avatarfood: 1,
    avatarentertainment:3,
    avatarsleep: 2
}

export const Icons = {
    animal_dealer: require('./people/animal_dealer.png'),
    warden: require('./people/warden.png'),
    ad_man: require('./people/ad_man.png'),
    CASH: require('./icon/CreditsT.png'),
    MEAT: require('./food/meat2.png'),
    [AdType.BILLBOARD]: require('./billboard.png'),
    [AdType.INTERNET]: require('./internet.png'),
    [AdType.RADIO]: require('./radio.png'),
    [AdType.TV]: require('./tv.png'),
    employeeAccident: require('./eaten.png'),
    meth: require('./meth.png'),
    lowEmployment: require('./no_employee.png'),
    no_meat: require('./no_meat.png'),
    shady_lender: require('./people/shady_investor.png'),
    builder: require('./people/builder.png'),
    phone: require('./cellphone.png'),
    cops: require('./people/cop.png'),
    audio: require('./audio.png'),
    doc: require('./people/tutorial.png'),
    TIGER: require('./Tigre.png'),
    ads: require('./ads.png'),
    sale: require('./sale.png'),
    convict: require('./convict.png'),
    construction: require('./construction.png')
}

export const Buildings = [
    {
        asset: require('./buildings/s_pen.png'),
        type: BuildingType.S_PEN,
        width: 32,
        height: 32,
        price: 100,
        description: 'Holds 5 animals',
        name: 'Small Cage',
        maxAnimals: 5
    },
    {
        asset: require('./buildings/m_pen.png'),
        type: BuildingType.M_PEN,
        width: 64,
        height: 32,
        price: 200,
        description: 'Holds 10 animals',
        name: 'Medium Cage',
        maxAnimals: 10
    },
    {
        asset: require('./buildings/giftshop.png'),
        type: BuildingType.GIFT_SHOP,
        width: 32,
        height: 32,
        price: 5000,
        description: 'Gift Shop increases cash if manned.',
        name: 'Gift Shop'
    },
    {
        asset: require('./buildings/petting_arena.png'),
        type: BuildingType.PETTING_ARENA,
        width: 32,
        height: 32,
        price: 5000,
        description: 'Supply the Cuddle Pit with young animals to generate cash',
        name: 'Cuddle Pit'
    },
    {
        asset: require('./buildings/snack_hut.png'),
        type: BuildingType.SNACK_HUT,
        width: 32,
        height: 32,
        price: 2000,
        description: 'Sells snax if manned and you have meat',
        name: 'Snack Hut'
    },
    {
        asset: require('./buildings/housing.png'),
        type: BuildingType.HOUSING,
        width: 32,
        height: 32,
        price: 1000,
        description: 'Employee trailer support 2 people',
        name: 'Trailer'
    },
    {
        asset: require('./buildings/studio.png'),
        type: BuildingType.STUDIO,
        width: 32,
        height: 32,
        price: 10000,
        description: 'Youtube channel gives advertising boost if manned',
        name: 'Studio'
    }
]